from io import BytesIO
from datetime import datetime
from flask import send_file
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle


def generate_candidate_report(data):
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(A4),
        rightMargin=30,
        leftMargin=30,
        topMargin=30,
        bottomMargin=30
    )

    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("<b>AI Resume Screening System</b>", styles["Title"]))
    elements.append(Paragraph("Professional Candidate Report", styles["Heading2"]))
    elements.append(Spacer(1, 10))

    generated_date = datetime.now().strftime("%d %B %Y, %I:%M %p")
    elements.append(Paragraph(f"<b>Generated Date:</b> {generated_date}", styles["Normal"]))
    elements.append(Paragraph("<b>Generated By:</b> Admin / HR", styles["Normal"]))
    elements.append(Spacer(1, 20))

    total = len(data)
    pending = len([row for row in data if row["status"] == "pending"])
    shortlisted = len([row for row in data if row["status"] == "shortlisted"])
    rejected = len([row for row in data if row["status"] == "rejected"])

    summary_data = [
        ["Total Candidates", "Pending", "Shortlisted", "Rejected"],
        [total, pending, shortlisted, rejected]
    ]

    summary_table = Table(summary_data, colWidths=[150, 150, 150, 150])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#111827")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#f3f4f6")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
    ]))

    elements.append(Paragraph("<b>Candidate Summary</b>", styles["Heading3"]))
    elements.append(summary_table)
    elements.append(Spacer(1, 25))

    table_data = [
        ["No", "Candidate", "Email", "Phone", "Status", "Uploaded Date"]
    ]

    for index, row in enumerate(data, start=1):
        uploaded = row["uploaded_at"].strftime("%d %b %Y") if row["uploaded_at"] else "-"

        table_data.append([
            index,
            row["candidate_name"],
            row["email"],
            row["phone"],
            row["status"].capitalize(),
            uploaded
        ])

    table = Table(table_data, colWidths=[40, 150, 180, 100, 100, 110])

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563eb")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9fafb")]),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
    ]))

    elements.append(Paragraph("<b>Candidate List</b>", styles["Heading3"]))
    elements.append(table)
    elements.append(Spacer(1, 25))

    elements.append(Paragraph(
        "<i>This report is confidential and generated by AI Resume Screening System.</i>",
        styles["Normal"]
    ))

    doc.build(elements)

    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name="professional_candidate_report.pdf",
        mimetype="application/pdf"
    )